name: JAR

on:
  push:
  workflow_dispatch:

jobs:
  jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          cache: gradle
          java-version: 25
      - name: Build plugin jars
        run: ./gradlew :worldedit-bukkit:assemble --no-configure-on-demand --no-daemon
      - name: Upload plugin jars
        uses: actions/upload-artifact@v7
        with:
          name: FastAsyncWorldEdit-${{ github.sha }}
          path: worldedit-bukkit/build/libs/FastAsyncWorldEdit-*.jar
          if-no-files-found: error
          retention-days: 90
